feat: add RANGE_CHECK builtins
ClementWalter/cairo-vm-gs pull request #19
Opened 2024-05-27 16:01 UTC by KeneePatel

# added RANGE_CHECK function

Time spent on this PR: 30 minutes

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

no function to range check.

Resolves #16 

## What is the new behavior?

Added a function `RANGE_CHECK` which takes `num: bigint` as an input and checks the range of the num. If the num < 2^128, it will throw an error, or else return num.

also: removed a `console.log()` which was slipped in and was not cleaned up.

2024-05-27 16:04 UTC, KeneePatel commented
I forgot to ask but should I keep the RC_BOUND const in the `builtins.ts` file or should I put that in `constants.ts`.

I felt the constant is only valid for range_check builtin so I put in `builtins.ts`, but lemme know if I should have put that in `constants.ts`.

2024-05-28 12:35 UTC, ClementWalter requested changes
see comment in the other PR, thx!

2024-06-01 23:43 UTC, KeneePatel commented
Shit I think I made an oops with rebasing ;-;
Lemme know if this will create any problem. I will branch through latest main again, and create a PR exactly same as this.

2024-06-03 15:26 UTC, ClementWalter approved these changes

2024-06-03 15:26 UTC, merged