feat: add bitwise builtins
ClementWalter/cairo-vm-gs pull request #21
Opened 2024-05-27 20:00 UTC by KeneePatel

# added bitwise builtins

Time spent on this PR: 30 mins

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

No builtin functions for bitwise operations.

Resolves #20 

## What is the new behavior?

Added four functions:
- BITWISE_AND
- BITWISE_XOR
- BITWISE_OR
- BITWISE_OPERATIONS

All functions take two inputs of a bigint and outputs a bigint as well.

The first three functions do what they are expected to, and the last function returns output of all three other functions wrapped in an array.

2024-05-28 12:09 UTC, ClementWalter commented on src/builtin.ts
> +}
this will not be useful in our context as the FUNCTION will directly be written in the cell

2024-05-29 19:59 UTC, ClementWalter commented on src/builtins/bitwise/bitwise.ts
> +}
we won't need this so YAGNI let's remove it

2024-05-29 20:01 UTC, ClementWalter commented on src/ui/Code.ts
good documentation, but tbf I think that it's better to define these functions with two inputs rather than on an array

is

```
BITWISE_AND(A1, A2)
```

looks better to me that

```
BITWISE_AND(A1:A2)
```

doesn't really make sense to take an array if it needs to have two inputs

2024-05-29 20:12 UTC, KeneePatel commented on src/ui/Code.ts
Thanks, I will change to have two inputs only.

2024-06-03 15:04 UTC, ClementWalter requested changes

2024-06-03 15:04 UTC, ClementWalter commented on src/builtins/bitwise/bitwise.ts
> +}
```suggestion
```

2024-06-03 15:05 UTC, ClementWalter approved these changes

2024-06-03 15:07 UTC, merged