Add python cairo0 poetry project
ClementWalter/cairo-vm-gs pull request #8
Opened 2024-03-20 00:11 UTC by JimmyFate

# Add python cairo0 poetry project

Time spent on this PR: 1h

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Resolves #7 

## What is the new behavior?

- added python poetry project with `cairo-lang` dependency
- added [fibonacci.cairo](https://github.com/ClementWalter/cairo-vm-gs/commit/2ccc41304ba8b862e47ac9c9be9b478b89c35954)

2024-03-20 08:57 UTC, ClementWalter requested changes
ok nice, I'd rather have the python project files (pyproject.toml and poetry.lock) at the root of the project

Plus can you compile and commit the built file?

should be `cairo-compile fibonacci.cairo --output fibonacci_compiled.json`

2024-03-20 20:52 UTC, JimmyFate commented
> ok nice, I'd rather have the python project files (pyproject.toml and poetry.lock) at the root of the project
> 
> Plus can you compile and commit the built file?
> 
> should be `cairo-compile fibonacci.cairo --output fibonacci_compiled.json`

Done 👍

2024-03-21 11:11 UTC, ClementWalter approved these changes

2024-03-21 11:11 UTC, ClementWalter commented
@JimmyFate is it the first time you see low level cairo 0 ? did you understand the program ?

2024-03-21 11:13 UTC, merged